### ISSUE TITLE
Erosion input validation fixes

### ISSUE THREAD

**Issue by knudsvik** [equinor/pysand#14]
- `D` boundaries in RP-O501 (0.01 - 1 m) should be stated in the warning
- `d_p` boundaries in RP-O501 (0.02 - 5 mm) should be stated in the warning
- When `D` and `d_p` are negative, they should not give result
- `alpha` in probes should be limited to 10-90 deg (page 34 in RP-O501)

Following parameters gave no error:
- `v_m` to be positive (limitations exist in RP-O501: 0-200)
- `rho_m` to be positive (limitations exist in RP-O501: 1-1500)
- `mu_m` to be positive (limitations exist in RP-O501: 1e-6-1e-2)
- `Q_s` to be positive (limitations exist in RP-O501: 0-500 ppmV)
- `R` to be positive (limitations exist in RP-O501: 0.5-50)

All above checked for bend model in version 1.2

**Comment by PoyiOstona** [comment]
Bullet point 3: which diameter should be taken for this condition when it is reducer, D1 or D2?

**Comment by knudsvik** [comment]
Do you mean for negative input? Neither one can be negative..

**Comment by PoyiOstona** [comment]
Bullet point 1: Does this apply for manifold and branch pipe diameters (D1, D2) ?

**Comment by knudsvik** [comment]
At least for branch diameter (D1), not sure about the D2 though so let's keep that out for now.

**Comment by PoyiOstona** [comment]
v_m, rho_m, mu_m, Q_s, R - If model boundaries for these values are exceeded, do you want errors or warnings?

**Comment by knudsvik** [comment]
Agreed. But it should not calculate when the inputs are negative though... how do you propose handling that?

**Comment by PoyiOstona** [comment]
Ah ok. Then maybe return np.nan when any of these is negative. What do you say?

**Comment by knudsvik** [comment]
Yes!
